// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAvatar: typeof import('./src/components/Global/AppAvatar/AppAvatar.vue')['default']
    AppFavButton: typeof import('./src/components/Global/AppFavButton/AppFavButton.vue')['default']
    AppLogo: typeof import('./src/components/Global/AppLogo/AppLogo.vue')['default']
    AppNavigation: typeof import('./src/components/Global/AppNavigation/AppNavigation.vue')['default']
    AppNavigationAvatar: typeof import('./src/components/Global/AppNavigationAvatar/AppNavigationAvatar.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    PageOffer: typeof import('./src/components/Page/PageOffer/PageOffer.vue')['default']
    PageOfferDetails: typeof import('./src/components/Page/PageOfferDetails/PageOfferDetails.vue')['default']
    PageOfferForm: typeof import('./src/components/Page/PageOfferForm/PageOfferForm.vue')['default']
    PageOfferGallery: typeof import('./src/components/Page/PageOfferGallery/PageOfferGallery.vue')['default']
    PageOfferMobileBar: typeof import('./src/components/Page/PageOfferMobileBar/PageOfferMobileBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test.vue')['default']
  }
}

export {}
